In [6]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB , MultinomialNB ,BernoulliNB
from sklearn.metrics import accuracy_score

In [15]:
df = pd.read_excel('/kaggle/input/datasets/ayahesham2002/churndata/churn_dataset.xlsx')

In [17]:
df

    Age  Tenure     Sex Churn
0    56       8    Male    No
1    46      63  Female    No
2    32      11  Female    No
3    60       8    Male    No
4    25      35    Male    No
..  ...     ...     ...   ...
95   24      38  Female    No
96   26      24    Male    No
97   41      69  Female   Yes
98   18      70    Male    No
99   61      11    Male    No

[100 rows x 4 columns]

In [21]:
df.isna().sum()

Age       0
Tenure    0
Sex       0
Churn     0
dtype: int64

In [22]:
label_map_churn = {'No': 0, 'Yes': 1}
label_map_sex   = {'Male': 1, 'Female': 0}

df["Churn"] = df["Churn"].map(label_map_churn)
df["Sex"]   = df["Sex"].map(label_map_sex)

In [24]:
df

    Age  Tenure  Sex  Churn
0    56       8    1      0
1    46      63    0      0
2    32      11    0      0
3    60       8    1      0
4    25      35    1      0
..  ...     ...  ...    ...
95   24      38    0      0
96   26      24    1      0
97   41      69    0      1
98   18      70    1      0
99   61      11    1      0

[100 rows x 4 columns]

In [28]:
features = ["Age", "Tenure", "Sex"]
x = df[features]
y = df["Churn"]
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [29]:
model=GaussianNB()

In [30]:
model.fit(x_train,y_train)

GaussianNB()

In [31]:
y_pred = model.predict(x_test)

In [32]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
accuracy_score(y_test,y_pred)

0.8

In [35]:
import joblib
joblib.dump(model,'Churn_model.pkl')

['Churn_model.pkl']